<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * EminentDomain implementation : © Alena Laskavaia <laskava@gmail.com>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * EminentDomain game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */




$this->token_types = array(
        // --- gen php begin ---
'deck' => [
  'type' => 'deck',
  'name' => clienttranslate("Deck"),
  'tooltip' => clienttranslate("Player's Card Deck"),
  'tooltip_action' => clienttranslate("Click to inspect"),
  'loc'=>2,'content'=>1,'counter'=>1 ,
],
'discard' => [
  'type' => 'discard',
  'name' => clienttranslate("Discard"),
  'tooltip' => clienttranslate("Player's Discard Pile"),
  'tooltip_action' => clienttranslate("Click to inspect"),
  'loc'=>2,'content'=>1,'counter'=>1 ,
],
'setaside' => [
  'type' => 'zone',
  'name' => clienttranslate("Set Aside Zone"),
],
'preferences' => [
  'type' => 'preferences',
  'name' => clienttranslate("User Preferences"),
  'loc'=>2,'content'=>0,'counter'=>0,'showname'=>false,
],
'hand' => [
  'type' => 'hand',
  'name' => clienttranslate("Hand"),
  'loc'=>2,'content'=>2,'counter'=>1,'showname'=>false ,
],
'handwrapper' => [
  'type' => 'handwrapper',
  'name' => clienttranslate("Hand Size"),
  'tooltip' => clienttranslate("Player's Current Hand Size"),
],
'tableau' => [
  'type' => 'tableau',
  'name' => clienttranslate("Empire"),
  'loc'=>2,'content'=>1,'counter'=>0,'showname'=>false ,
],
'discard_planets' => [
  'type' => 'discard_planets',
  'name' => clienttranslate("Planets Discard"),
  'tooltip' => clienttranslate("Planets Discard Pile"),
  'tooltip_action' => clienttranslate("Click to inspect"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_planets' => [
  'type' => 'supply_planets',
  'name' => clienttranslate("Planets Deck"),
  'tooltip' => clienttranslate("Planets Supply Deck"),
  'tooltip_action' => clienttranslate("Cannot inspect"),
  'loc'=>1,'content'=>0,'counter'=>1 ,
],
'fighter_F' => [
  'type' => 'fighter',
  'name' => clienttranslate("Fighter"),
  'p'=>'F',
],
'fighter_j1' => [
  'type' => 'fighter fighter_F',
  'name' => clienttranslate("Fighter"),
  'p'=>'F',
],
'fighter_D' => [
  'type' => 'fighter',
  'name' => clienttranslate("Destroyer"),
  'p'=>'D',
],
'fighter_B' => [
  'type' => 'fighter',
  'name' => clienttranslate("Battlecruiser"),
  'tooltip' => clienttranslate("You may only have 1 [Battlecruiser] in play at a time. While in play, it is worth 2 and grants you a 1 discount (2 with Improved Fleet) on all Warfare costs."),
  'p'=>'B', 'hid'=>'BATTLECRUISER',
],
'card_fleet_b' => [
  'type' => 'card fleet fleet_basic tech  sprite_tilesE actionable',
  'name' => clienttranslate("Basic Fleet"),
  'tooltip' => clienttranslate("Discard 3 [Fighter] to gain a [Destroyer] (x1) OR Discard 2 [Destroyer] to gain a [Battlecruiser] (x1). <p><p>You may only have 1 [Battlecruiser] in play at a time. While in play, it is worth 2 VP and grants you 1 [Fighter] discount (with Basic Fleet) on all Warfare costs. <p>When leading or following a Research role, you may upgrade Basic Fleet to Improved Fleet by paying 3 [Research] or 3 [Fighter]."),
  'hid'=>'BASIC_FLEET', 'b'=>3, 'bm'=>'3F', 't'=>'M', 'a'=>'FFF>D/DD>B', 'side'=>1,
],
'card_fleet_i' => [
  'type' => 'card fleet fleet_advanced tech sprite_tilesE actionable',
  'name' => clienttranslate("Improved Fleet"),
  'tooltip' => clienttranslate("For every 2 [Fighter] you discard in this action, gain 1 [Destroyer] OR Discard 2 [Destroyer] to gain a [Battlecruiser] (x1). <p>You may spend 1 [Battlecruiser] when attacking any Planet instead of the printed Warfare cost. <p>You may only have 1 [Battlecruiser] in play at a time. While in play, it is worth 2 VP and grants you 2 [Fighter] discount (with Improved Fleet) on all Warfare costs."),
  'hid'=>'IMPROVED_FLEET', 'p'=>'','a'=>'FF>D+/DD>B','b'=>3, 'bm'=>'3F', 'flip'=>'card_fleet_b', 'side'=>2,
],
'stock' => [
  'type' => 'stock',
  'name' => clienttranslate("General Supply"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'vp' => [
  'type' => 'vp',
  'name' => clienttranslate("Influence"),
],
'tableau_fighter' => [
  'type' => 'fighter_counter',
  'name' => clienttranslate("Fighter Counter"),
  'tooltip' => clienttranslate("Shows how many fighters you have"),
],
'tableau_vp' => [
  'type' => 'vp_counter',
  'name' => clienttranslate("Influence Counter"),
  'tooltip' => clienttranslate("Shows how many Influence tokens you have"),
],
'resource_w' => [
  'type' => 'resource_w',
  'name' => clienttranslate("Water"),
  'p'=>'w',
],
'resource_f' => [
  'type' => 'resource_f',
  'name' => clienttranslate("Food"),
  'p'=>'f',
],
'resource_i' => [
  'type' => 'resource_i',
  'name' => clienttranslate("Iron"),
  'p'=>'i',
],
'resource_s' => [
  'type' => 'resource_s',
  'name' => clienttranslate("Silicon"),
  'p'=>'s',
],
'iconperm_C' => [
  'type' => 'icon C',
  'name' => clienttranslate("Settle Permanents"),
  'tooltip' => clienttranslate("When settling subtract number of visible settle symbols from planet requirement"),
],
'iconperm_W' => [
  'type' => 'icon W',
  'name' => clienttranslate("Warfare Permanents"),
  'tooltip' => clienttranslate("When collecting fighters add number of visible warfare symbols to total count"),
],
'iconperm_S' => [
  'type' => 'icon S',
  'name' => clienttranslate("Survey Permanents"),
  'tooltip' => clienttranslate("When surveying planets add number of visible survey symbols to total count"),
],
'iconperm_P' => [
  'type' => 'icon P',
  'name' => clienttranslate("Produce Permanents"),
  'tooltip' => clienttranslate("When producing resources add number of visible produce symbols to total count"),
],
'iconperm_T' => [
  'type' => 'icon T',
  'name' => clienttranslate("Trade Permanents"),
  'tooltip' => clienttranslate("When trading resources add number of visible trade symbols to total count"),
],
'iconperm_R' => [
  'type' => 'icon R',
  'name' => clienttranslate("Research Permanents"),
  'tooltip' => clienttranslate("When researching technology add number of visible research symbols to total count"),
],
'supply_survey' => [
  'type' => 'supply',
  'name' => clienttranslate("Survey Roles Deck"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_warfare' => [
  'type' => 'supply',
  'name' => clienttranslate("Warfare Roles Deck"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_colonize' => [
  'type' => 'supply',
  'name' => clienttranslate("Colonize Roles Deck"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_produce' => [
  'type' => 'supply',
  'name' => clienttranslate("Produce Roles Deck"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_research' => [
  'type' => 'supply',
  'name' => clienttranslate("Research Roles Deck"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_tech_A' => [
  'type' => 'supply',
  'name' => clienttranslate("Advanced Technologies"),
  'tooltip' => clienttranslate("Play Research Role to select any Technology you can afford."),
  'tooltip_action' => clienttranslate("Click to expand/collapse"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_tech_E' => [
  'type' => 'supply',
  'name' => clienttranslate("Fertile Technologies"),
  'tooltip' => clienttranslate("Play Research Role to select any Technology you can afford."),
  'tooltip_action' => clienttranslate("Click to expand/collapse"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_tech_M' => [
  'type' => 'supply',
  'name' => clienttranslate("Metallic Technologies"),
  'tooltip' => clienttranslate("Play Research Role to select any Technology you can afford."),
  'tooltip_action' => clienttranslate("Click to expand/collapse"),
  'loc'=>1,'content'=>1,'counter'=>1 ,
],
'supply_survey_counter' => [
  'type' => 'supply_counter',
  'name' => clienttranslate("Supply Card Counter"),
  'tooltip' => clienttranslate("This number indicates how many cards left in the deck."),
],
'supply_warfare_counter' => [
  'type' => 'supply_counter',
  'name' => clienttranslate("Supply Card Counter"),
  'tooltip' => clienttranslate("This number indicates how many cards left in the deck."),
],
'supply_colonize_counter' => [
  'type' => 'supply_counter',
  'name' => clienttranslate("Supply Card Counter"),
  'tooltip' => clienttranslate("This number indicates how many cards left in the deck."),
],
'supply_produce_counter' => [
  'type' => 'supply_counter',
  'name' => clienttranslate("Supply Card Counter"),
  'tooltip' => clienttranslate("This number indicates how many cards left in the deck."),
],
'supply_research_counter' => [
  'type' => 'supply_counter',
  'name' => clienttranslate("Supply Card Counter"),
  'tooltip' => clienttranslate("This number indicates how many cards left in the deck."),
],
'card_role_warfare' => [
  'type' => 'card_role',
  'name' => clienttranslate("Warfare"),
  'tooltip' => clienttranslate("ACTION: Attack 1 Planet OR Collect 1 Fighter<br/><br/>ROLE: Collect 1 Fighter per <div class='icon warfare'></div><br/><span class='yellow'>Leader:</span> May attack 1 Planet instead"),
  'b'=>0,'p'=>'','i'=>'W','v'=>0,'a'=>'a/F','r'=>'W', 'l'=>'a',
],
'card_role_survey' => [
  'type' => 'card_role',
  'name' => clienttranslate("Survey"),
  'tooltip' => clienttranslate("ACTION: Draw 2 Cards<br/><br/>ROLE: Look at <div class='icon survey'></div> - 1 planet cards, keep 1<br/> <span class='yellow'>Leader:</span> Look at 1 additional card"),
  'b'=>0,'p'=>'','i'=>'S','v'=>0,'a'=>'dd','r'=>'S', 'l'=>'v',
],
'card_role_colonize' => [
  'type' => 'card_role',
  'name' => clienttranslate("Colonize"),
  'tooltip' => clienttranslate("ACTION: Settle 1 Planet OR +1 Colony<br/><br/>ROLE: +1 Colony per <div class='icon colonize'></div><br/><span class='yellow'>Leader:</span> May settle 1 Planet instead"),
  'b'=>0,'p'=>'','i'=>'C','v'=>0,'a'=>'s','r'=>'C','l'=>'s',
],
'card_role_produce' => [
  'type' => 'card_role',
  'name' => clienttranslate("Produce/Trade"),
  'tooltip' => clienttranslate("<h2>Produce</h2><div>ACTION: Produce 1 resource<br/><br/>ROLE: Produce 1 resource per <div class='icon produce'></div></div><h2>Trade</h2><div>ACTION: Trade 1 resource for <div class='icon vp'></div><br/><br/>ROLE: Trade 1 resource per <div class='icon trade'></div> for 1 <div class='icon vp'></div> each</div>"),
  'b'=>0,'p'=>'','i'=>'PT','v'=>0,'a'=>'p/t','r'=>'P/T','l'=>'',
],
'card_role_research' => [
  'type' => 'card_role',
  'name' => clienttranslate("Research"),
  'tooltip' => clienttranslate("ACTION: Remove up to 2 cards in hand from the game<br/><br/>ROLE: Acquire 1 technology card after satisfying <div class='icon research'></div> cost and planet requirements"),
  'b'=>0,'p'=>'','i'=>'R','v'=>0,'a'=>'ee!','r'=>'R','l'=>'',
],
'card_role_politics' => [
  'type' => 'card_role',
  'name' => clienttranslate("Politics"),
  'tooltip' => clienttranslate("ACTION: Remove this card from the game. Take 1 Role card from the stocks into your hand."),
  'b'=>0,'p'=>'','i'=>'','v'=>0,'a'=>'l',
],
'x_warfare_bottom' => [
  'type' => 'card_role',
  'name' => clienttranslate("Warfare"),
  'tooltip' => clienttranslate("ROLE: +<div class='icon warfare'></div>. Collect 1 Fighter per <div class='icon warfare'></div><br/><span class='yellow'>Leader:</span> May attack 1 Planet instead"),
  'b'=>0,'p'=>'','i'=>'W','v'=>0,'a'=>'a/F','r'=>'W', 'l'=>'a',
],
'x_survey_bottom' => [
  'type' => 'card_role',
  'name' => clienttranslate("Survey"),
  'tooltip' => clienttranslate("ACTION: Draw 2 Cards<br/><br/>ROLE: Look at <div class='icon survey'></div> - 1 planet cards, keep 1<br/> <span class='yellow'>Leader:</span> Look at 1 additional card"),
  'b'=>0,'p'=>'','i'=>'S','v'=>0,'a'=>'dd','r'=>'S', 'l'=>'v',
],
'x_colonize_bottom' => [
  'type' => 'card_role',
  'name' => clienttranslate("Colonize"),
  'tooltip' => clienttranslate("ACTION: Settle 1 Planet OR +1 Colony<br/><br/>ROLE: +1 Colony per <div class='icon colonize'></div><br/><span class='yellow'>Leader:</span> May settle 1 Planet instead"),
  'b'=>0,'p'=>'','i'=>'C','v'=>0,'a'=>'s','r'=>'C','l'=>'s',
],
'x_produce_bottom' => [
  'type' => 'card_role',
  'name' => clienttranslate("Produce/Trade"),
  'tooltip' => clienttranslate("<h2>Produce</h2><div>ACTION: Produce 1 resource<br/><br/>ROLE: Produce 1 resource per <div class='icon produce'></div></div><h2>Trade</h2><div>ACTION: Trade 1 resource for influence<br/><br/>ROLE: Trade 1 resource per <div class='icon trade'></div> for 1 influence each</div>"),
  'b'=>0,'p'=>'','i'=>'PT','v'=>0,'a'=>'p/t','r'=>'P/T','l'=>'',
],
'x_research_bottom' => [
  'type' => 'card_role',
  'name' => clienttranslate("Research"),
  'tooltip' => clienttranslate("ROLE: Acquire 1 technology card after satisfying <div class='icon research'></div> cost and planet requirements"),
  'b'=>0,'p'=>'','i'=>'R','v'=>0,'a'=>'ee!','r'=>'R','l'=>'',
],
'card_planet_1_1' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Lyttle"),
  't'=>'A','i'=>'R', 'slots'=>'s', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_1_2' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Echo Rose"),
  't'=>'A','i'=>'R', 'slots'=>'s', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_1_3' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Srod Avain N2"),
  't'=>'A','i'=>'R', 'slots'=>'', 'v'=>4,'w'=>6,'c'=>3,
],
'card_planet_1_4' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Ral Gai'Gaw"),
  't'=>'A','i'=>'T', 'slots'=>'s', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_1_5' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Hanoj - T"),
  't'=>'A','i'=>'T', 'slots'=>'s', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_1_6' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Zhephan"),
  't'=>'A','i'=>'T', 'slots'=>'', 'v'=>4,'w'=>6,'c'=>3,
],
'card_planet_1_7' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Oknow"),
  't'=>'A','i'=>'', 'slots'=>'s', 'v'=>2,'h'=>1,'w'=>5,'c'=>4,
],
'card_planet_1_8' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Sima-07C"),
  't'=>'A','i'=>'', 'slots'=>'s', 'v'=>2,'h'=>1,'w'=>4,'c'=>5,
],
'card_planet_1_9' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Sholmican"),
  't'=>'A','i'=>'', 'slots'=>'s', 'v'=>4,'w'=>6,'c'=>3,
],
'card_planet_2_1' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Styku"),
  't'=>'E','i'=>'C', 'slots'=>'w', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_2_2' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Mik-Mik"),
  't'=>'E','i'=>'C', 'slots'=>'f', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_2_3' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("New Texas"),
  't'=>'E','i'=>'C', 'slots'=>'fw', 'v'=>2,'w'=>6,'c'=>3,
],
'card_planet_2_4' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Gerdland"),
  't'=>'E','i'=>'P', 'slots'=>'w', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_2_5' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Mishburr ITO-A"),
  't'=>'E','i'=>'P', 'slots'=>'f', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_2_6' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Artigas GNS-111"),
  't'=>'E','i'=>'P', 'slots'=>'fw', 'v'=>2,'w'=>6,'c'=>3,
],
'card_planet_2_7' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Spielbany VI"),
  't'=>'E','i'=>'', 'slots'=>'w', 'v'=>2,'h'=>1,'w'=>5,'c'=>4,
],
'card_planet_2_8' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Nelos IV"),
  't'=>'E','i'=>'', 'slots'=>'f', 'v'=>2,'h'=>1,'w'=>4,'c'=>5,
],
'card_planet_2_9' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Angus Daffy"),
  't'=>'E','i'=>'', 'slots'=>'fw', 'v'=>3,'w'=>6,'c'=>3,
],
'card_planet_3_1' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Voson"),
  't'=>'M','i'=>'S', 'slots'=>'i', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_3_2' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Pink Sonar"),
  't'=>'M','i'=>'S', 'slots'=>'i', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_3_3' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Kyrie & Juno"),
  't'=>'M','i'=>'S', 'slots'=>'', 'v'=>4,'w'=>6,'c'=>3,
],
'card_planet_3_4' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Tankahshin"),
  't'=>'M','i'=>'W', 'slots'=>'i', 'v'=>3,'w'=>5,'c'=>4,
],
'card_planet_3_5' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Erkam-W"),
  't'=>'M','i'=>'W', 'slots'=>'i', 'v'=>3,'w'=>4,'c'=>5,
],
'card_planet_3_6' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Overlord Betzel's Domain"),
  't'=>'M','i'=>'W', 'slots'=>'', 'v'=>4,'w'=>6,'c'=>3,
],
'card_planet_3_7' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Marghannah Prime"),
  't'=>'M','i'=>'', 'slots'=>'', 'v'=>3,'h'=>1,'w'=>5,'c'=>4,
],
'card_planet_3_8' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("8910 Spielen"),
  't'=>'M','i'=>'', 'slots'=>'i', 'v'=>2,'h'=>1,'w'=>4,'c'=>5,
],
'card_planet_3_9' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Idroyos"),
  't'=>'M','i'=>'', 'slots'=>'', 'v'=>5,'w'=>6,'c'=>3,
],
'card_planet_0_1' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Pomerene"),
  't'=>'A','i'=>'', 'slots'=>'s', 'v'=>2,'w'=>2,'c'=>2,
],
'card_planet_0_2' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Drawde"),
  't'=>'E','i'=>'', 'slots'=>'f', 'v'=>2,'w'=>2,'c'=>2,
],
'card_planet_0_3' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Piedra Seca"),
  't'=>'M','i'=>'', 'slots'=>'i', 'v'=>2,'w'=>2,'c'=>2,
],
'card_planet_0_4' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Mesia Sednim"),
  't'=>'E','i'=>'', 'slots'=>'w', 'v'=>2,'w'=>2,'c'=>2,
],
'card_planet_0_5' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Chrispen"),
  't'=>'M','i'=>'', 'slots'=>'i', 'v'=>2,'w'=>2,'c'=>2,
],
'card_planet_0_6' => [
  'type' => 'planet card_planet',
  'name' => clienttranslate("Liagiba"),
  't'=>'A','i'=>'', 'slots'=>'s', 'v'=>2,'w'=>2,'c'=>2,
],
        // --- gen php end ---
        // --- gen php begin basic_tech ---
// #||||b- research|p – prereq|I – symbols|v - influence|A - action||flip – id of flip card|e perm action|||
'card_tech_1_11' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Survey"),
  'b' => 3,
  'p' => 'A',
  'i' => 'ST',
  'v' => 0,
  'a' => 'ddd',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 3 cards."),
],
'card_tech_1_12' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Survey"),
  'b' => 3,
  'p' => 'A',
  'i' => 'SR',
  'v' => 0,
  'a' => 'ddd',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 3 cards."),
],
'card_tech_1_13' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Survey"),
  'b' => 3,
  'p' => 'E',
  'i' => 'SC',
  'v' => 0,
  'a' => 'ddd',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 3 cards."),
],
'card_tech_1_14' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Survey"),
  'b' => 3,
  'p' => 'E',
  'i' => 'SP',
  'v' => 0,
  'a' => 'ddd',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 3 cards."),
],
'card_tech_1_21' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Colonize"),
  'b' => 3,
  'p' => 'A',
  'i' => 'CR',
  'v' => 0,
  'a' => 'Ss',
  'side' => 0,
  'tooltip' => clienttranslate("Settle 1 Planet. Settle another planet OR +1 Colony."),
],
'card_tech_1_22' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Colonize"),
  'b' => 3,
  'p' => 'A',
  'i' => 'CT',
  'v' => 0,
  'a' => 'Ss',
  'side' => 0,
  'tooltip' => clienttranslate("Settle 1 Planet. Settle another planet OR +1 Colony."),
],
'card_tech_1_23' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Colonize"),
  'b' => 3,
  'p' => 'M',
  'i' => 'CS',
  'v' => 0,
  'a' => 'Ss',
  'side' => 0,
  'tooltip' => clienttranslate("Settle 1 Planet. Settle another planet OR +1 Colony."),
],
'card_tech_1_24' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Colonize"),
  'b' => 3,
  'p' => 'M',
  'i' => 'CW',
  'v' => 0,
  'a' => 'Ss',
  'side' => 0,
  'tooltip' => clienttranslate("Settle 1 Planet. Settle another planet OR +1 Colony."),
],
'card_tech_1_31' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Warfare"),
  'b' => 3,
  'p' => 'A',
  'i' => 'WR',
  'v' => 0,
  'a' => 'FF/a',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 2 Fighters OR Attack 1 Planet."),
],
'card_tech_1_32' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Warfare"),
  'b' => 3,
  'p' => 'A',
  'i' => 'WT',
  'v' => 0,
  'a' => 'FF/a',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 2 Fighters OR Attack 1 Planet."),
],
'card_tech_1_33' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Warfare"),
  'b' => 3,
  'p' => 'E',
  'i' => 'WC',
  'v' => 0,
  'a' => 'FF/a',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 2 Fighters OR Attack 1 Planet."),
],
'card_tech_1_34' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Warfare"),
  'b' => 3,
  'p' => 'E',
  'i' => 'WP',
  'v' => 0,
  'a' => 'FF/a',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 2 Fighters OR Attack 1 Planet."),
],
'card_tech_1_41' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Production"),
  'b' => 3,
  'p' => 'A',
  'i' => 'PR',
  'v' => 0,
  'a' => 'pp',
  'side' => 0,
  'tooltip' => clienttranslate("Produce 2 Resources."),
],
'card_tech_1_42' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Production"),
  'b' => 3,
  'p' => 'A',
  'i' => 'PT',
  'v' => 0,
  'a' => 'pp',
  'side' => 0,
  'tooltip' => clienttranslate("Produce 2 Resources."),
],
'card_tech_1_43' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Production"),
  'b' => 3,
  'p' => 'M',
  'i' => 'PS',
  'v' => 0,
  'a' => 'pp',
  'side' => 0,
  'tooltip' => clienttranslate("Produce 2 Resources."),
],
'card_tech_1_44' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Production"),
  'b' => 3,
  'p' => 'M',
  'i' => 'PW',
  'v' => 0,
  'a' => 'pp',
  'side' => 0,
  'tooltip' => clienttranslate("Produce 2 Resources."),
],
'card_tech_1_51' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Trade"),
  'b' => 3,
  'p' => 'E',
  'i' => 'TP',
  'v' => 0,
  'a' => 'i',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence from the supply."),
],
'card_tech_1_52' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Trade"),
  'b' => 3,
  'p' => 'E',
  'i' => 'TC',
  'v' => 0,
  'a' => 'i',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence from the supply."),
],
'card_tech_1_53' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Trade"),
  'b' => 3,
  'p' => 'M',
  'i' => 'TS',
  'v' => 0,
  'a' => 'i',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence from the supply."),
],
'card_tech_1_54' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Trade"),
  'b' => 3,
  'p' => 'M',
  'i' => 'TW',
  'v' => 0,
  'a' => 'i',
  'side' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence from the supply."),
],
'card_tech_1_61' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Research"),
  'b' => 3,
  'p' => 'E',
  'i' => 'RP',
  'v' => 0,
  'a' => 'd.eee!',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 1 Card. Remove up to 3 cards in hand from the game."),
],
'card_tech_1_62' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Research"),
  'b' => 3,
  'p' => 'E',
  'i' => 'RC',
  'v' => 0,
  'a' => 'd.eee!',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 1 Card. Remove up to 3 cards in hand from the game."),
],
'card_tech_1_63' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Research"),
  'b' => 3,
  'p' => 'M',
  'i' => 'RS',
  'v' => 0,
  'a' => 'd.eee!',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 1 Card. Remove up to 3 cards in hand from the game."),
],
'card_tech_1_64' => [
  'type' => 'tech',
  'name' => clienttranslate("Improved Research"),
  'b' => 3,
  'p' => 'M',
  'i' => 'RW',
  'v' => 0,
  'a' => 'd.eee!',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 1 Card. Remove up to 3 cards in hand from the game."),
],
'card_tech_2_71' => [
  'type' => 'tech',
  'name' => clienttranslate("Diverse Markets"),
  'b' => 5,
  'p' => 'AA',
  'i' => 'RT',
  'v' => 2,
  'a' => '?',
  'side' => 0,
  'eot'=>'div_r','lasting'=>true,
  'tooltip' => clienttranslate("+1 Influence for each TYPE of Resource you trade this turn."),
],
'card_tech_2_72' => [
  'type' => 'tech',
  'name' => clienttranslate("Data Network"),
  'b' => 5,
  'p' => 'AA',
  'i' => 'RR',
  'v' => 2,
  'a' => 'dd.E',
  'side' => 0,
  'tooltip' => clienttranslate("Draw 2 Cards. Remove any number of cards in hand from the game."),
],
'card_tech_2_73' => [
  'type' => 'tech',
  'name' => clienttranslate("Specialization"),
  'b' => 5,
  'p' => 'AA',
  'i' => 'TT',
  'v' => 2,
  'a' => 'y',
  'side' => 0,
  'eot'=>'max_r','lasting'=>true,
  'tooltip' => clienttranslate("Choose 1 Resource TYPE.<br> +1 Influence for each resource of that TYPE you trade this turn."),
],
'card_tech_2_74' => [
  'type' => 'tech',
  'name' => clienttranslate("Weapon Emporium"),
  'b' => 5,
  'p' => 'AA',
  'v' => 2,
  'side' => 1,
  'flip' => 'card_tech_2_75',
  'tooltip' => clienttranslate("You may trade Fighters as if they were Resources."),
],
'card_tech_2_75' => [
  'type' => 'tech',
  'name' => clienttranslate("Streamlining"),
  'b' => 5,
  'p' => 'AA',
  'v' => 2,
  'side' => 2,
  'flip' => 'card_tech_2_74',
  'e' => 'e!',
  'tooltip' => clienttranslate("You may remove 1 card in hand from the game each turn."),
],
'card_tech_3_76' => [
  'type' => 'tech',
  'name' => clienttranslate("Adaptability"),
  'b' => 7,
  'p' => 'AAA',
  'v' => 5,
  'side' => 1,
  'flip' => 'card_tech_3_77',
  'tooltip' => clienttranslate("Your standard Research Role cards gain all symbols. They can be used to boost or follow any role."),
],
'card_tech_3_77' => [
  'type' => 'tech',
  'name' => clienttranslate("Hyperefficiency"),
  'b' => 7,
  'p' => 'AAA',
  'v' => 5,
  'side' => 2,
  'flip' => 'card_tech_3_76',
  'e' => 'E',
  'tooltip' => clienttranslate("You may remove any number of cards from hand each turn."),
],
'card_tech_2_81' => [
  'type' => 'tech',
  'name' => clienttranslate("Mobilization"),
  'b' => 5,
  'p' => 'MM',
  'i' => 'SW',
  'v' => 2,
  'a' => 'FF',
  'side' => 0,
  'e' => 'a',
  'trig'=>'l-.:a/x','lasting'=>1,
  'tooltip' => clienttranslate("Collect 2 Fighters. You may Attack 1 Planet after your Role Phase this turn."),
],
'card_tech_2_82' => [
  'type' => 'tech',
  'name' => clienttranslate("Survey Team"),
  'b' => 5,
  'p' => 'MM',
  'i' => 'SS',
  'v' => 2,
  'a' => 'u',
  'side' => 0,
  'tooltip' => clienttranslate("Take top Planet of the planet deck and put it into your Empire face down."),
],
'card_tech_2_83' => [
  'type' => 'tech',
  'name' => clienttranslate("War Path"),
  'b' => 5,
  'p' => 'MM',
  'i' => 'WW',
  'v' => 2,
  'a' => 'aa',
  'side' => 0,
  'tooltip' => clienttranslate("Attack up to 2 Planets."),
],
'card_tech_2_84' => [
  'type' => 'tech',
  'name' => clienttranslate("Imperialism"),
  'b' => 5,
  'p' => 'MM',
  'i' => 'STW',
  'v' => 2,
  'side' => 1,
  'flip' => 'card_tech_2_85',
],
'card_tech_2_85' => [
  'type' => 'tech',
  'name' => clienttranslate("Scorched Earth Policy"),
  'b' => 5,
  'p' => 'MM',
  'v' => 2,
  'side' => 2,
  'flip' => 'card_tech_2_84',
  'tooltip' => clienttranslate("-2 to your Warfare costs. When you Attack a Planet leave a Fighter on it. That Planet cannot store resources."),
],
'card_tech_3_86' => [
  'type' => 'tech',
  'name' => clienttranslate("Logistics"),
  'b' => 7,
  'p' => 'MMM',
  'v' => 5,
  'side' => 1,
  'flip' => 'card_tech_3_87',
  'tooltip' => clienttranslate("Play the Action and Role phases of your turn in any order. At the end of the game, take an additional turn."),
  'rulings' => 'This rule is from Escalation errata.',
],
'card_tech_3_87' => [
  'type' => 'tech',
  'name' => clienttranslate("Productivity"),
  'b' => 7,
  'p' => 'MMM',
  'v' => 5,
  'side' => 2,
  'flip' => 'card_tech_3_86',
  'tooltip' => clienttranslate("You may play an additional card for its Action effect during your Action phase."),
],
'card_tech_2_91' => [
  'type' => 'tech',
  'name' => clienttranslate("Artificial Intelligence"),
  'b' => 5,
  'p' => 'EE',
  'i' => 'CP',
  'v' => 2,
  'a' => 'll',
  'side' => 0,
  'tooltip' => clienttranslate("Take any 2 Role cards from the stacks into your hand."),
],
'card_tech_2_92' => [
  'type' => 'tech',
  'name' => clienttranslate("Genetic Engineering"),
  'b' => 5,
  'p' => 'EE',
  'i' => 'PP',
  'v' => 2,
  'a' => '?',
  'side' => 0,
  'eot'=>'div_r','lasting'=>true,
  'tooltip' => clienttranslate("+1 Influence for each TYPE of Resource your produce this turn."),
],
'card_tech_2_93' => [
  'type' => 'tech',
  'name' => clienttranslate("Terraforming"),
  'b' => 5,
  'p' => 'EE',
  'i' => 'CC',
  'v' => 2,
  'a' => 'c',
  'side' => 0,
  'tooltip' => clienttranslate("Add this card to a Planet as 2 Colonies. If this fulfills Colonized cost, Settle the planet."),
  'rulings' => 'Terraforming can be used in conjunction with Colonize symbols on Planets and permanent Technology cards in your Empire. This rule is from Escalation Errata.',
],
'card_tech_2_94' => [
  'type' => 'tech',
  'name' => clienttranslate("Fertile Ground"),
  'b' => 5,
  'p' => 'EE',
  'i' => 'CPR',
  'v' => 2,
  'side' => 1,
  'flip' => 'card_tech_2_95',
],
'card_tech_2_95' => [
  'type' => 'tech',
  'name' => clienttranslate("Abundance"),
  'b' => 5,
  'p' => 'EE',
  'v' => 2,
  'side' => 2,
  'flip' => 'card_tech_2_94',
  'trig'=>['enter:pppp','settle:pp','attack:pp'],
  'tooltip' => clienttranslate("Produce 4 Resources. When you Settle or Attack a Planet produce 2 Resources."),
  'rulings' => 'This rule is from Escalation errata.',
],
'card_tech_3_96' => [
  'type' => 'tech',
  'name' => clienttranslate("Dissension"),
  'b' => 7,
  'p' => 'EEE',
  'v' => 5,
  'side' => 1,
  'flip' => 'card_tech_3_97',
  'tooltip' => clienttranslate("Draw 1 additional card when Dissenting."),
],
'card_tech_3_97' => [
  'type' => 'tech',
  'name' => clienttranslate("Bureaucracy"),
  'b' => 7,
  'p' => 'EEE',
  'v' => 5,
  'side' => 2,
  'flip' => 'card_tech_3_96',
  'tooltip' => clienttranslate("When following a role +<div class='icon survey'></div><div class='icon warfare'></div><div class='icon produce'></div><div class='icon trade'></div><div class='icon research'></div>.<p> You may use Leader Bonus when Following the Colonize and Warfare roles."),
  'rulings' => 'This rule is from Escalation errata.',
],
        // --- gen php end basic_tech ---
        
        // --- gen php begin escalation_tech ---
// #--- EDIT IN EXCEL --- |||card name|number in pdf|number in sprite|side 0 single,1 front, 2 back|planet type|action codes||direct php code|permanent|research cost|military cost|cost|influence points|symbol icons|produce slots||action/card text/tooltip|
'card_tech_E_1' => [
  'type' => 'tech tech_E tech_E_1',
  'exp' => 'E',
  'name' => clienttranslate("PEACE TREATY"),
  'cnum' => 4,
  'sp' => 1,
  'side' => 1,
  't' => 'A',
  'trig'=>'peace',
  'b' => 3,
  'bm' => '3F',
  'p' => 'A',
  'v' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
  'rulings' => 'Multiple Peace Treaty abilities from Tech cards and Planets stack.',
],
'card_tech_E_2' => [
  'type' => 'tech tech_E tech_E_2',
  'exp' => 'E',
  'name' => clienttranslate("FREEDOM OF TRADE"),
  'cnum' => 4,
  'sp' => 2,
  'side' => 2,
  't' => 'A',
  'b' => 3,
  'bm' => '3F',
  'p' => 'A',
  'v' => 0,
  'i' => 'TT',
  'tooltip' => clienttranslate("You may follow Produce roles as if they were Trade roles. You may follow Trade roles as if they were Produce roles."),
],
'card_tech_E_3' => [
  'type' => 'tech tech_E tech_E_3',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED RESEARCH"),
  'cnum' => 5,
  'sp' => 3,
  'side' => 0,
  't' => 'A',
  'a' => 'd.eee!',
  'b' => 3,
  'bm' => '3F',
  'p' => 'A',
  'v' => 0,
  'i' => 'RF',
  'tooltip' => clienttranslate("Draw 1 card. Remove up to 3 cards in hand from the game."),
],
'card_tech_E_4' => [
  'type' => 'tech tech_E tech_E_4',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED TRADE"),
  'cnum' => 6,
  'sp' => 4,
  'side' => 0,
  't' => 'A',
  'a' => 'i',
  'b' => 3,
  'bm' => '3F',
  'p' => 'A',
  'v' => 0,
  'i' => 'TF',
  'tooltip' => clienttranslate("Collect 1 Influence from the supply."),
],
'card_tech_E_5' => [
  'type' => 'tech tech_E tech_E_5',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 7,
  'sp' => 5,
  'side' => 0,
  't' => 'A',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'AN',
  'v' => 0,
  'i' => 'Rs',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_6' => [
  'type' => 'tech tech_E tech_E_6',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 8,
  'sp' => 6,
  'side' => 0,
  't' => 'A',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'AN',
  'v' => 0,
  'i' => 'Ts',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_7' => [
  'type' => 'tech tech_E tech_E_7',
  'exp' => 'E',
  'name' => clienttranslate("SCIENTIFIC DISCOVERY"),
  'cnum' => 9,
  'sp' => 7,
  'side' => 0,
  't' => 'A',
  'a' => 'To',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AA',
  'v' => 2,
  'i' => 'Rs',
  'tooltip' => clienttranslate("Take any tech card costing [3 Research symbols] or less and put it into your hand. You do not need the prerequisite Planets. You may play an additional action during this Action phase."),
  'rulings' => 'If you gained a permanent technology card it goes to into play not in hand.',
],
'card_tech_E_8' => [
  'type' => 'tech tech_E tech_E_8',
  'exp' => 'E',
  'name' => clienttranslate("SOLDIERS OF FORTUNE"),
  'cnum' => 10,
  'sp' => 8,
  'side' => 0,
  't' => 'A',
  'a' => 'D>iii',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AA',
  'v' => 2,
  'i' => 'D',
  'tooltip' => clienttranslate("Discard 1 [Destroyer]. If you do, collect 3 Influence from the supply."),
],
'card_tech_E_9' => [
  'type' => 'tech tech_E tech_E_9',
  'exp' => 'E',
  'name' => clienttranslate("SCIENTIFIC METHOD"),
  'cnum' => 11,
  'sp' => 9,
  'side' => 1,
  't' => 'A',
  'trig'=>'l-R:R',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AA',
  'v' => 2,
  'i' => 'R',
  'tooltip' => clienttranslate("You may purchase 1 additional Tech card when LEADING a Research role. Pay costs and prereq's for each separately."),
  'rulings' => '<li>Each Planet may only be used as a prerequisite once per Research role. Therefore, if you were to purchase two Level 2 Advanced Technology cards, you would need FOUR Advanced Planets.<li> Each Research symbol may only be used once per Role phase, so it may not be used to pay for both of your purchases.<li>Effects of the first purchased card resolve before second purchase so it can affect it.',
],
'card_tech_E_10' => [
  'type' => 'tech tech_E tech_E_10',
  'exp' => 'E',
  'name' => clienttranslate("DEFENSE CONTRACT"),
  'cnum' => 11,
  'sp' => 10,
  'side' => 2,
  't' => 'A',
  'e'=>'t/F>i',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AA',
  'v' => 2,
  'tooltip' => clienttranslate("Once per turn you may discard 1 Resource or 1 [Fighter] to collect 1 Influence from the supply."),
],
'card_tech_E_11' => [
  'type' => 'tech tech_E tech_E_11',
  'exp' => 'E',
  'name' => clienttranslate("INDUSTRIAL ESPIONAGE"),
  'cnum' => 12,
  'sp' => 11,
  'side' => 0,
  't' => 'A',
  'a' => 'i',
  'b' => 7,
  'bm' => '1B',
  'p' => 'AAA',
  'v' => 3,
  'i' => 'B',
  'tooltip' => clienttranslate("Each opponent must return 1 Influence token to the supply. Collect 1 Influence from the supply."),
  'rulings' => 'Returning Influence tokens to the supply does not Untrigger end of game if it was previously triggerred by running out of influence tokens.',
],
'card_tech_E_12' => [
  'type' => 'tech tech_E tech_E_12',
  'exp' => 'E',
  'name' => clienttranslate("PEACE TREATY"),
  'cnum' => 13,
  'sp' => 12,
  'side' => 1,
  't' => 'E',
  'trig'=>'peace',
  'b' => 3,
  'bm' => '3F',
  'p' => 'E',
  'v' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
  'rulings' => 'Multiple Peace Treaty abilities from Tech cards and Planets stack.',
],
'card_tech_E_13' => [
  'type' => 'tech tech_E tech_E_13',
  'exp' => 'E',
  'name' => clienttranslate("BIOSPHERE"),
  'cnum' => 13,
  'sp' => 13,
  'side' => 2,
  't' => 'E',
  'b' => 3,
  'bm' => '3F',
  'p' => 'E',
  'v' => 0,
  'slots' => 'nn',
  'tooltip' => clienttranslate("[Resource slot - Any type] [Resource slot - Any type]"),
],
'card_tech_E_14' => [
  'type' => 'tech tech_E tech_E_14',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED COLONIZE"),
  'cnum' => 14,
  'sp' => 14,
  'side' => 0,
  't' => 'E',
  'a' => 'Ss',
  'b' => 3,
  'bm' => '3F',
  'p' => 'E',
  'v' => 0,
  'i' => 'CF',
  'tooltip' => clienttranslate("Settle 1 Planet. Settle another Planet OR +1 Colony."),
],
'card_tech_E_15' => [
  'type' => 'tech tech_E tech_E_15',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED PRODUCTION"),
  'cnum' => 15,
  'sp' => 15,
  'side' => 0,
  't' => 'E',
  'a' => 'pp',
  'b' => 3,
  'bm' => '3F',
  'p' => 'E',
  'v' => 0,
  'i' => 'PF',
  'tooltip' => clienttranslate("Produce 2 Resources."),
],
'card_tech_E_16' => [
  'type' => 'tech tech_E tech_E_16',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 16,
  'sp' => 16,
  'side' => 0,
  't' => 'E',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'EN',
  'v' => 0,
  'i' => 'Cf',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_17' => [
  'type' => 'tech tech_E tech_E_17',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 17,
  'sp' => 17,
  'side' => 0,
  't' => 'E',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'EN',
  'v' => 0,
  'i' => 'Pw',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_18' => [
  'type' => 'tech tech_E tech_E_18',
  'exp' => 'E',
  'name' => clienttranslate("SPECIALIZED PRODUCTION"),
  'cnum' => 18,
  'sp' => 18,
  'side' => 0,
  't' => 'E',
  'a' => 'y',
  'lasting'=>1,'eot'=>'max_r',
  'b' => 5,
  'bm' => '2D',
  'p' => 'EE',
  'v' => 2,
  'i' => 'Cf',
  'tooltip' => clienttranslate("Choose a resource type. Collect 1 Influence for each resource of that type you produce this turn."),
],
'card_tech_E_19' => [
  'type' => 'tech tech_E tech_E_19',
  'exp' => 'E',
  'name' => clienttranslate("SPOILS OF WAR"),
  'cnum' => 19,
  'sp' => 19,
  'side' => 0,
  't' => 'E',
  'a' => '%Fp',
  'b' => 5,
  'bm' => '2D',
  'p' => 'EE',
  'v' => 2,
  'i' => 'D',
  'tooltip' => clienttranslate("Produce 1 Resource for each [Fighter] in your Empire."),
],
'card_tech_E_20' => [
  'type' => 'tech tech_E tech_E_20',
  'exp' => 'E',
  'name' => clienttranslate("BLACK MARKET"),
  'cnum' => 20,
  'sp' => 20,
  'side' => 1,
  't' => 'E',
  'b' => 5,
  'bm' => '2D',
  'p' => 'EE',
  'v' => 2,
  'tooltip' => clienttranslate("You may discard resources from your empire as if they were symbols to boost or follow any role."),
],
'card_tech_E_21' => [
  'type' => 'tech tech_E tech_E_21 coloniseable',
  'exp' => 'E',
  'name' => clienttranslate("COLONY SHIP"),
  'cnum' => 20,
  'sp' => 21,
  'side' => 2,
  't' => 'E',
  'e'=>'c',
  'b' => 5,
  'bm' => '2D',
  'p' => 'EE',
  'v' => 2,
  'tooltip' => clienttranslate("Colony Ship holds Colonies. Once per turn: +1 Colony. When Settling you may redistribute Colonies in your Empire."),
  'rulings' => 'The +1 Colony is added as a “free action” at any point during your turn. Adding a Colony is optional. When redistributing Colonies, you may move any Colony, not just those on Colony Ship. Colonies may be redistributed regardless of whether you lead or follow the role, but not when dissenting the role.',
],
'card_tech_E_22' => [
  'type' => 'tech tech_E tech_E_22',
  'exp' => 'E',
  'name' => clienttranslate("NATURAL ORDER"),
  'cnum' => 21,
  'sp' => 22,
  'side' => 0,
  't' => 'E',
  'a' => 'g',
  'b' => 7,
  'bm' => '1B',
  'p' => 'EEE',
  'v' => 3,
  'i' => 'B',
  'tooltip' => clienttranslate("Remove one permanent technology from the game. Its owner receives REPARATIONS: 2 Influence from the supply."),
  'rulings' => '<li> You only can target permanent technology in play <li> You can target your own permanent technology',
],
'card_tech_E_23' => [
  'type' => 'tech tech_E tech_E_23',
  'exp' => 'E',
  'name' => clienttranslate("PEACE TREATY"),
  'cnum' => 22,
  'sp' => 23,
  'side' => 1,
  't' => 'M',
  'trig'=>'peace',
  'b' => 3,
  'bm' => '3F',
  'p' => 'M',
  'v' => 0,
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
  'rulings' => 'Multiple Peace Treaty abilities from Tech cards and Planets stack.',
],
'card_tech_E_24' => [
  'type' => 'tech tech_E tech_E_24',
  'exp' => 'E',
  'name' => clienttranslate("THOROUGH SURVEY"),
  'cnum' => 22,
  'sp' => 24,
  'side' => 2,
  't' => 'M',
  'special'=>'qqQ!',
  'b' => 3,
  'bm' => '3F',
  'p' => 'M',
  'v' => 0,
  'tooltip' => clienttranslate("Survey Role: You may draw 2 fewer Planet cards. If you do, keep 1 additional Planet."),
],
'card_tech_E_25' => [
  'type' => 'tech tech_E tech_E_25',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED SURVEY"),
  'cnum' => 23,
  'sp' => 25,
  'side' => 0,
  't' => 'M',
  'a' => 'ddd',
  'b' => 3,
  'bm' => '3F',
  'p' => 'M',
  'v' => 0,
  'i' => 'SF',
  'tooltip' => clienttranslate("Draw 3 cards."),
],
'card_tech_E_26' => [
  'type' => 'tech tech_E tech_E_26',
  'exp' => 'E',
  'name' => clienttranslate("IMPROVED WARFARE"),
  'cnum' => 24,
  'sp' => 26,
  'side' => 0,
  't' => 'M',
  'a' => 'FF/a',
  'b' => 3,
  'bm' => '3F',
  'p' => 'M',
  'v' => 0,
  'i' => 'WF',
  'tooltip' => clienttranslate("Collect 2 Fighters OR Attack 1 Planet."),
],
'card_tech_E_27' => [
  'type' => 'tech tech_E tech_E_27',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 25,
  'sp' => 27,
  'side' => 0,
  't' => 'M',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'MN',
  'v' => 0,
  'i' => 'Si',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_28' => [
  'type' => 'tech tech_E tech_E_28',
  'exp' => 'E',
  'name' => clienttranslate("DOUBLE TIME"),
  'cnum' => 26,
  'sp' => 28,
  'side' => 0,
  't' => 'M',
  'a' => 'oo',
  'b' => 3,
  'bm' => '3F',
  'p' => 'MN',
  'v' => 0,
  'i' => 'Wi',
  'tooltip' => clienttranslate("You may play 2 additional actions during this Action phase."),
],
'card_tech_E_29' => [
  'type' => 'tech tech_E tech_E_29',
  'exp' => 'E',
  'name' => clienttranslate("DEEP SPACE PROBES"),
  'cnum' => 27,
  'sp' => 29,
  'side' => 0,
  't' => 'M',
  'a' => 'Lo',
  'b' => 5,
  'bm' => '2D',
  'p' => 'MM',
  'v' => 2,
  'i' => 'Si',
  'tooltip' => clienttranslate("RECON the Planet deck for 1 card. You may play an additional action during this Action phase."),
],
'card_tech_E_30' => [
  'type' => 'tech tech_E tech_E_30',
  'exp' => 'E',
  'name' => clienttranslate("DESTROYER TECHNOLOGY"),
  'cnum' => 28,
  'sp' => 30,
  'side' => 0,
  't' => 'M',
  'a' => 'DD',
  'b' => 5,
  'bm' => '2D',
  'p' => 'MM',
  'v' => 2,
  'i' => 'FF',
  'tooltip' => clienttranslate("Collect 2 [Destroyer] from the supply."),
],
'card_tech_E_31' => [
  'type' => 'tech tech_E tech_E_31',
  'exp' => 'E',
  'name' => clienttranslate("WEALTH OF KNOWLEDGE"),
  'cnum' => 29,
  'sp' => 31,
  'side' => 1,
  't' => 'M',
  'b' => 5,
  'bm' => '2D',
  'p' => 'MM',
  'v' => 2,
  'tooltip' => clienttranslate("You may use standard Survey cards to Boost (NOT Follow) any role."),
],
'card_tech_E_32' => [
  'type' => 'tech tech_E tech_E_32',
  'exp' => 'E',
  'name' => clienttranslate("WARFARE TECHNOLOGY"),
  'cnum' => 29,
  'sp' => 32,
  'side' => 2,
  't' => 'M',
  'b' => 5,
  'bm' => '2D',
  'p' => 'MM',
  'v' => 2,
  'tooltip' => clienttranslate("You may discard [Fighter] as if they were [Research] to boost or follow Research roles."),
],
'card_tech_E_33' => [
  'type' => 'tech tech_E tech_E_33',
  'exp' => 'E',
  'name' => clienttranslate("TOUR DE FORCE"),
  'cnum' => 30,
  'sp' => 33,
  'side' => 0,
  't' => 'M',
  'a' => 'DFF',
  'lasting'=>1,'trig'=>'l-.:a/x',
  'b' => 7,
  'bm' => '1B',
  'p' => 'MMM',
  'v' => 3,
  'i' => 'B',
  'tooltip' => clienttranslate("Collect 1 [Destroyer] and 2 [Fighter] from the supply. You may Attack a planet after any Role phase this turn."),
],
'card_tech_E_34' => [
  'type' => 'tech tech_E tech_E_34',
  'exp' => 'E',
  'name' => clienttranslate("ELEVATED INCENTIVES"),
  'cnum' => 31,
  'sp' => 34,
  'side' => 0,
  't' => 'D',
  'a' => 'O',
  'b' => 3,
  'bm' => '3F',
  'p' => 'AEM',
  'v' => 0,
  'i' => 'D',
  'tooltip' => clienttranslate("Take an additional Role phase this turn. Opponents may follow or dissent as normal."),
],
'card_tech_E_35' => [
  'type' => 'tech tech_E tech_E_35',
  'exp' => 'E',
  'name' => clienttranslate("SYNTHESIZE"),
  'cnum' => 32,
  'sp' => 35,
  'side' => 0,
  't' => 'D',
  'a' => 'Kdo',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AEM',
  'v' => 2,
  'i' => 'n',
  'tooltip' => clienttranslate("RECON your deck for any 1 card. Draw 1 card. You may play an additional action during this Action phase."),
],
'card_tech_E_36' => [
  'type' => 'tech tech_E tech_E_36',
  'exp' => 'E',
  'name' => clienttranslate("ANNEX"),
  'cnum' => 33,
  'sp' => 36,
  'side' => 0,
  't' => 'D',
  'a' => 'a',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AEM',
  'v' => 2,
  'i' => 'nF',
  'tooltip' => clienttranslate("Attack a face down planet in an opponent's Empire. That player receives REPARATIONS: 2 Influence from the supply."),
  'rulings' => 'You must pay the Warfare cost as normal, modified by any benefits you may have. You may never look at the front of a face down Planet card in an opponent\'s Empire. After Attacking, place the Planet face up in your Empire.',
],
'card_tech_E_37' => [
  'type' => 'tech tech_E tech_E_37',
  'exp' => 'E',
  'name' => clienttranslate("OVERSIGHT COMMITTEE"),
  'cnum' => 34,
  'sp' => 37,
  'side' => 1,
  't' => 'D',
  'a' => 'dd.ee!',
  'h'=>1,
  'b' => 5,
  'bm' => '2D',
  'p' => 'AEM',
  'v' => 2,
  'tooltip' => clienttranslate("Draw 2 cards, then remove up to 2 cards in hand from the game."),
],
'card_tech_E_38' => [
  'type' => 'tech tech_E tech_E_38',
  'exp' => 'E',
  'name' => clienttranslate("MILITARY CAMPAIGN"),
  'cnum' => 34,
  'sp' => 38,
  'side' => 2,
  't' => 'D',
  'rep'=>'ii',
  'b' => 5,
  'bm' => '2D',
  'p' => 'AEM',
  'v' => 2,
  'tooltip' => clienttranslate("You may pay [1 Battlecruiser] and X [Fighter] equal to the planet's Influence to Attack opponents' face up Planets. REPARATIONS: 2 Influence from the supply."),
  'rulings' => 'You receive the Planet in the same condition as it was before the Attack: Resources remain in Resource slots, and Scorched Earth penalties remain. This is not a Warfare cost, so discounts (and pentalties) from Scorched Earth Policy and Fleet/Improved Fleet do not apply.',
],
'card_tech_E_39' => [
  'type' => 'tech tech_E tech_E_39',
  'exp' => 'E',
  'name' => clienttranslate("WELL OILED MACHINE"),
  'cnum' => 35,
  'sp' => 39,
  'side' => 1,
  't' => 'D',
  'e'=>'O',
  'b' => 7,
  'bm' => '1B',
  'p' => 'AEM',
  'v' => 3,
  'tooltip' => clienttranslate("You may take an additional Role phase each turn. If you do, opponents may follow or dissent."),
],
'card_tech_E_40' => [
  'type' => 'tech tech_E tech_E_40',
  'exp' => 'E',
  'name' => clienttranslate("ELITE SQUADRON"),
  'cnum' => 35,
  'sp' => 40,
  'side' => 2,
  't' => 'D',
  'b' => 7,
  'bm' => '1B',
  'p' => 'AEM',
  'v' => 3,
  'rslots' => 'DFF',
  'tooltip' => clienttranslate("[Replenishing Destroyer icon and 2 Replenishing Fighter icons]"),
],
        // --- gen php end escalation_tech ---
        
        // --- gen php begin scenarios ---
// #id|||title|||Start Planet|Surver cards|Warfare cards|Colonize cards|Produce/Trade|Research cards|Politics cards|@starting_tech1|@starting_tech2|@starting_tech3|'setup’=>[{s},{w},{c},{t},{r},{p},(‘{planet}’),(‘{t1}’)]
'scenario_10' => [
  'type' => 'scenario card scenario_e_1',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("SCORCHED EARTH"),
  'cnum' => 1,
  'expR' => 'B',
  'planet' => 'Piedra Seca',
  's' => 2,
  'w' => 1,
  'c' => 2,
  't' => 0,
  'r' => 1,
  'p' => 2,
  't1' => 'SCORCHED EARTH POLICY',
  'setup'=>[2,1,2,0,1,2,('Piedra Seca'),('SCORCHED EARTH POLICY')],
],
'scenario_8' => [
  'type' => 'scenario card scenario_e_2',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("FERTILE GROUND"),
  'cnum' => 2,
  'expR' => 'B',
  'planet' => 'Drawde',
  's' => 0,
  'w' => 0,
  'c' => 3,
  't' => 2,
  'r' => 2,
  'p' => 1,
  't1' => 'FERTILE GROUND',
  'setup'=>[0,0,3,2,2,1,('Drawde'),('FERTILE GROUND')],
],
'scenario_11' => [
  'type' => 'scenario card scenario_e_3',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("STREAMLINED"),
  'cnum' => 3,
  'expR' => 'B',
  'planet' => 'Liagiba',
  's' => 3,
  'w' => 1,
  'c' => 1,
  't' => 3,
  'r' => 1,
  'p' => 1,
  't1' => 'STREAMLINING',
  'setup'=>[3,1,1,3,1,1,('Liagiba'),('STREAMLINING')],
],
'scenario_7' => [
  'type' => 'scenario card scenario_e_4',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("EXPLORER"),
  'cnum' => 4,
  'expR' => 'B',
  'planet' => 'random',
  's' => 0,
  'w' => 1,
  'c' => 2,
  't' => 2,
  'r' => 2,
  'p' => 2,
  't1' => 'SURVEY TEAM',
  'setup'=>[0,1,2,2,2,2,('random'),('SURVEY TEAM')],
],
'scenario_6' => [
  'type' => 'scenario card scenario_e_5',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("ARTIFICIAL INTELLIGENCE"),
  'cnum' => 5,
  'expR' => 'B',
  'planet' => 'random',
  's' => 0,
  'w' => 0,
  'c' => 0,
  't' => 0,
  'r' => 0,
  'p' => 0,
  't1' => 'ARTIFICIAL INTELLIGENCE',
  'setup'=>[0,0,0,0,0,0,('random'),('ARTIFICIAL INTELLIGENCE')],
],
'scenario_9' => [
  'type' => 'scenario card scenario_e_6',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("IMPERIALISM"),
  'cnum' => 6,
  'expR' => 'B',
  'planet' => 'random',
  's' => 2,
  'w' => 0,
  'c' => 2,
  't' => 2,
  'r' => 2,
  'p' => 2,
  't1' => 'IMPERIALISM',
  'setup'=>[2,0,2,2,2,2,('random'),('IMPERIALISM')],
],
'scenario_17' => [
  'type' => 'scenario card scenario_e_7',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("WARMONGER"),
  'cnum' => 7,
  'expR' => 'E',
  'planet' => 'Bardolph',
  's' => 2,
  'w' => 2,
  'c' => 2,
  't' => 0,
  'r' => 2,
  'p' => 2,
  't1' => 'MILITARY CAMPAIGN',
  'setup'=>[2,2,2,0,2,2,('Bardolph'),('MILITARY CAMPAIGN')],
],
'scenario_18' => [
  'type' => 'scenario card scenario_e_8',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("SCIENTIFIC DISCOVERY"),
  'cnum' => 8,
  'expR' => 'E',
  'planet' => 'Bardolph',
  's' => 2,
  'w' => 1,
  'c' => 2,
  't' => 2,
  'r' => 0,
  'p' => 1,
  't1' => 'SCIENTIFIC DISCOVERY',
  'setup'=>[2,1,2,2,0,1,('Bardolph'),('SCIENTIFIC DISCOVERY')],
],
'scenario_19' => [
  'type' => 'scenario card scenario_e_9',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("BIOSPHERE"),
  'cnum' => 9,
  'expR' => 'E',
  'planet' => 'Angel Aniv Ek-625',
  's' => 3,
  'w' => 0,
  'c' => 3,
  't' => 0,
  'r' => 2,
  'p' => 0,
  't1' => 'BIOSPHERE',
  't2' => 'card_tech_E_15',
  't3' => 'card_tech_E_4',
  'setup'=>[3,0,3,0,2,0,('Angel Aniv Ek-625'),('BIOSPHERE'),'card_tech_E_15','card_tech_E_4'],
],
'scenario_110' => [
  'type' => 'scenario card scenario_e_10',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("COLONY SHIP"),
  'cnum' => 10,
  'expR' => 'E',
  'planet' => 'Angel Aniv Ek-625',
  's' => 2,
  'w' => 0,
  'c' => 4,
  't' => 2,
  'r' => 2,
  'p' => 0,
  't1' => 'COLONY SHIP',
  'setup'=>[2,0,4,2,2,0,('Angel Aniv Ek-625'),('COLONY SHIP')],
],
'scenario_111' => [
  'type' => 'scenario card scenario_e_11',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("DESTROYER"),
  'cnum' => 11,
  'expR' => 'E',
  'planet' => 'Kaeth',
  's' => 2,
  'w' => 0,
  'c' => 2,
  't' => 2,
  'r' => 2,
  'p' => 1,
  't1' => 'DESTROYER TECHNOLOGY',
  'setup'=>[2,0,2,2,2,1,('Kaeth'),('DESTROYER TECHNOLOGY')],
],
'scenario_112' => [
  'type' => 'scenario card scenario_e_12',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("BATTLECRUISER"),
  'cnum' => 12,
  'expR' => 'E',
  'planet' => 'Kaeth',
  's' => 2,
  'w' => 1,
  'c' => 1,
  't' => 2,
  'r' => 2,
  'p' => 2,
  't1' => 'IMPROVED FLEET',
  't2' => 'BATTLECRUISER',
  'setup'=>[2,1,1,2,2,2,('Kaeth'),('IMPROVED FLEET'),('BATTLECRUISER')],
],
'scenario_113' => [
  'type' => 'scenario card scenario_e_13',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("KNOWLEDGE IS POWER"),
  'cnum' => 13,
  'expR' => 'E',
  'planet' => 'Janus',
  's' => 2,
  'w' => 0,
  'c' => 0,
  't' => 0,
  'r' => 0,
  'p' => 3,
  't1' => 'WEALTH OF KNOWLEDGE',
  'setup'=>[2,0,0,0,0,3,('Janus'),('WEALTH OF KNOWLEDGE')],
],
'scenario_114' => [
  'type' => 'scenario card scenario_e_14',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("BLACK MARKET"),
  'cnum' => 14,
  'expR' => 'E',
  'planet' => 'Janus',
  's' => 2,
  'w' => 1,
  'c' => 1,
  't' => 2,
  'r' => 2,
  'p' => 2,
  't1' => 'BLACK MARKET',
  'setup'=>[2,1,1,2,2,2,('Janus'),('BLACK MARKET')],
],
'scenario_115' => [
  'type' => 'scenario card scenario_e_15',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("ARMS DEALER"),
  'cnum' => 15,
  'expR' => 'E',
  'planet' => 'Chaconos',
  's' => 2,
  'w' => 2,
  'c' => 1,
  't' => 2,
  'r' => 2,
  'p' => 1,
  't1' => 'WEAPON EMPORIUM',
  'setup'=>[2,2,1,2,2,1,('Chaconos'),('WEAPON EMPORIUM')],
],
'scenario_116' => [
  'type' => 'scenario card scenario_e_16',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("SPOILS OF WAR"),
  'cnum' => 16,
  'expR' => 'E',
  'planet' => 'Chaconos',
  's' => 2,
  'w' => 2,
  'c' => 2,
  't' => 1,
  'r' => 2,
  'p' => 0,
  't1' => 'SPOILS OF WAR',
  't2' => 'BIOSPHERE',
  'setup'=>[2,2,2,1,2,0,('Chaconos'),('SPOILS OF WAR'),('BIOSPHERE')],
],
'scenario_117' => [
  'type' => 'scenario card scenario_e_17',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("ABUNDANCE"),
  'cnum' => 17,
  'expR' => 'E',
  'planet' => 'Wiesbaden',
  's' => 2,
  'w' => 1,
  'c' => 2,
  't' => 2,
  'r' => 2,
  'p' => 1,
  't1' => 'ABUNDANCE',
  't2' => 'THOROUGH SURVEY',
  'setup'=>[2,1,2,2,2,1,('Wiesbaden'),('ABUNDANCE'),('THOROUGH SURVEY')],
],
'scenario_118' => [
  'type' => 'scenario card scenario_e_18',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("OVERSEER"),
  'cnum' => 18,
  'expR' => 'E',
  'planet' => 'Wiesbaden',
  's' => 3,
  'w' => 1,
  'c' => 1,
  't' => 1,
  'r' => 1,
  'p' => 3,
  't1' => 'OVERSIGHT COMMITTEE',
  'setup'=>[3,1,1,1,1,3,('Wiesbaden'),('OVERSIGHT COMMITTEE')],
],
'scenario_1' => [
  'type' => 'scenario card scenario_e_20',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("Mobilized"),
  'cnum' => 20,
  'expR' => 'B',
  'planet' => 'random',
  's' => 1,
  'w' => 1,
  'c' => 0,
  't' => 2,
  'r' => 2,
  'p' => 3,
  't1' => 'card_tech_2_81',
  'setup'=>[1,1,0,2,2,3,('random'),('card_tech_2_81')],
],
'scenario_2' => [
  'type' => 'scenario card scenario_e_21',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("War Path"),
  'cnum' => 21,
  'expR' => 'B',
  'planet' => 'card_planet_0_5',
  's' => 3,
  'w' => 2,
  'c' => 0,
  't' => 2,
  'r' => 2,
  'p' => 0,
  't1' => 'card_tech_2_83',
  'setup'=>[3,2,0,2,2,0,('card_planet_0_5'),('card_tech_2_83')],
],
'scenario_3' => [
  'type' => 'scenario card scenario_e_22',
  'tooltip' => clienttranslate("Game Scenario.<p> Special: Each of your resource slots can hold +1 resource"),
  'name' => clienttranslate("Bountiful Harvest"),
  'cnum' => 22,
  'expR' => 'B',
  'planet' => 'card_planet_0_4',
  's' => 3,
  'w' => 2,
  'c' => 3,
  't' => 1,
  'r' => 1,
  'p' => 0,
  't1' => 'card_tech_2_95',
  'setup'=>[3,2,3,1,1,0,('card_planet_0_4'),('card_tech_2_95')],
],
'scenario_4' => [
  'type' => 'scenario card scenario_e_23',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("Terraformer"),
  'cnum' => 23,
  'expR' => 'B',
  'planet' => 'random',
  's' => 3,
  'w' => 0,
  'c' => 1,
  't' => 1,
  'r' => 2,
  'p' => 2,
  't1' => 'card_tech_2_93',
  'setup'=>[3,0,1,1,2,2,('random'),('card_tech_2_93')],
],
'scenario_5' => [
  'type' => 'scenario card scenario_e_24',
  'tooltip' => clienttranslate("Game Scenario"),
  'name' => clienttranslate("Network Admin"),
  'cnum' => 24,
  'expR' => 'B',
  'planet' => 'card_planet_0_1',
  's' => 2,
  'w' => 2,
  'c' => 2,
  't' => 1,
  'r' => 0,
  'p' => 2,
  't1' => 'card_tech_2_72',
  'setup'=>[2,2,2,1,0,2,('card_planet_0_1'),('card_tech_2_72')],
],
        // --- gen php end scenarios ---
        // --- gen php begin escalation_planets ---
// #|#Category|Name||||Type|Warfare Cost|Colonize Cost||Resource1|||Influence||Game Text
'card_planet_ES_1' => [
  'name' => clienttranslate("Chaconos"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_1 sprite_tilesE',
  'sp' => 1,
  't' => 'P',
  'w' => 2,
  'c' => 2,
  'i' => 'T',
  'slots' => 'n',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_ES_2' => [
  'name' => clienttranslate("Janus"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_2 sprite_tilesE',
  'sp' => 2,
  't' => 'P',
  'w' => 2,
  'c' => 2,
  'i' => 'P',
  'slots' => 'n',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_ES_3' => [
  'name' => clienttranslate("Wiesbaden"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_5 sprite_tilesE',
  'sp' => 5,
  't' => 'P',
  'w' => 2,
  'c' => 2,
  'i' => 'S',
  'slots' => 'n',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_ES_4' => [
  'name' => clienttranslate("Bardolph"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_6 sprite_tilesE',
  'sp' => 6,
  't' => 'A',
  'w' => 5,
  'c' => 5,
  'i' => 'TR',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_ES_5' => [
  'name' => clienttranslate("Angel Aniv Ek-625"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_4 sprite_tilesE',
  'sp' => 4,
  't' => 'E',
  'w' => 5,
  'c' => 5,
  'i' => 'PC',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_ES_6' => [
  'name' => clienttranslate("Kaeth"),
  'expR' => 'E',
  'type' => 'planet start_planet sprite_tilesE_3 sprite_tilesE',
  'sp' => 3,
  't' => 'M',
  'w' => 5,
  'c' => 5,
  'i' => 'SW',
  'v' => 2,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_E_1' => [
  'name' => clienttranslate("Ny'Seia"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_1 sprite_planetsE',
  'sp' => 1,
  't' => 'A',
  'w' => 'D',
  'c' => 4,
  'a' => 'ee!',
  'v' => 4,
  'tooltip' => clienttranslate("Remove up to 2 cards in hand from the game"),
],
'card_planet_E_2' => [
  'name' => clienttranslate("Otto Erdesz"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_3 sprite_planetsE',
  'sp' => 3,
  't' => 'A',
  'w' => 'D',
  'c' => 4,
  'slots' => 's',
  'a' => 'tt',
  'v' => 3,
  'tooltip' => clienttranslate("Trade 2 Resources for 1 Influence each"),
],
'card_planet_E_3' => [
  'name' => clienttranslate("Terra Prime"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_5 sprite_planetsE',
  'sp' => 5,
  't' => 'E',
  'w' => 'D',
  'c' => 4,
  'a' => 'S',
  'v' => 4,
  'tooltip' => clienttranslate("Settle 1 Planet"),
],
'card_planet_E_4' => [
  'name' => clienttranslate("Vierra"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_7 sprite_planetsE',
  'sp' => 7,
  't' => 'E',
  'w' => 'D',
  'c' => 4,
  'slots' => 'fw',
  'a' => 'pp',
  'v' => 2,
  'tooltip' => clienttranslate("Produce 2 Resources"),
],
'card_planet_E_5' => [
  'name' => clienttranslate("Nalarad"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_9 sprite_planetsE',
  'sp' => 9,
  't' => 'M',
  'w' => 'D',
  'c' => 4,
  'a' => 'a',
  'v' => 4,
  'tooltip' => clienttranslate("Attack 1 Planet"),
],
'card_planet_E_6' => [
  'name' => clienttranslate("Monos"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_11 sprite_planetsE',
  'sp' => 11,
  't' => 'M',
  'w' => 'D',
  'c' => 4,
  'slots' => 'i',
  'a' => 'dd',
  'v' => 3,
  'tooltip' => clienttranslate("Draw 2 Cards"),
],
'card_planet_E_7' => [
  'name' => clienttranslate("Nakagawa Kozi"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_13 sprite_planetsE',
  'sp' => 13,
  't' => 'A',
  'w' => 'B',
  'c' => 4,
  'v' => 4,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_8' => [
  'name' => clienttranslate("Kaylexa"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_15 sprite_planetsE',
  'sp' => 15,
  't' => 'A',
  'w' => 'B',
  'c' => 4,
  'slots' => 's',
  'v' => 3,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_9' => [
  'name' => clienttranslate("Gregor Duffy"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_17 sprite_planetsE',
  'sp' => 17,
  't' => 'E',
  'w' => 'B',
  'c' => 4,
  'slots' => 'f',
  'v' => 3,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_10' => [
  'name' => clienttranslate("Orracle"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_19 sprite_planetsE',
  'sp' => 19,
  't' => 'E',
  'w' => 'B',
  'c' => 4,
  'slots' => 'w',
  'v' => 3,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_11' => [
  'name' => clienttranslate("Matusiak"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_21 sprite_planetsE',
  'sp' => 21,
  't' => 'M',
  'w' => 'B',
  'c' => 4,
  'v' => 4,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_12' => [
  'name' => clienttranslate("Yago"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_23 sprite_planetsE',
  'sp' => 23,
  't' => 'M',
  'w' => 'B',
  'c' => 4,
  'v' => 4,
  'trig'=>'peace',
  'tooltip' => clienttranslate("Collect 1 Influence when Dissenting a Warfare Role."),
],
'card_planet_E_13' => [
  'name' => clienttranslate("Pappathan Prime"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_25 sprite_planetsE',
  'sp' => 25,
  't' => 'A',
  'w' => 'D',
  'c' => 99,
  'slots' => 's',
  'rslots' => 'F',
  'v' => 3,
  'tooltip' => clienttranslate("[Replenishing Fighter Slot]"),
],
'card_planet_E_14' => [
  'name' => clienttranslate("Odonata"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_27 sprite_planetsE',
  'sp' => 27,
  't' => 'E',
  'w' => 'D',
  'c' => 99,
  'slots' => 'fw',
  'rslots' => 'F',
  'v' => 2,
  'tooltip' => clienttranslate("[Replenishing Fighter Slot]"),
],
'card_planet_E_15' => [
  'name' => clienttranslate("Pitt of Injustice"),
  'expR' => 'E',
  'type' => 'planet sprite_planetsE_29 sprite_planetsE',
  'sp' => 29,
  't' => 'M',
  'w' => 'D',
  'c' => 99,
  'rslots' => 'F',
  'v' => 4,
  'tooltip' => clienttranslate("[Replenishing Fighter Slot]"),
],
'card_planet_EP_1' => [
  'name' => clienttranslate("Magrathea"),
  'expR' => 'E',
  'type' => 'planet ',
  'sp' => 1,
  't' => 'P',
  'w' => 2,
  'c' => 2,
  'v' => 4,
  'tooltip' => clienttranslate("[Start Planet Tile]"),
],
'card_planet_EP_2' => [
  'name' => clienttranslate("Dionysus"),
  'expR' => 'E',
  'type' => 'planet ',
  'sp' => 2,
  't' => 'U',
  'w' => 6,
  'c' => 5,
  'slots' => 'n',
  'v' => 2,
  'h'=>1,
  'tooltip' => clienttranslate("Hand Size +1"),
],
'card_planet_EP_3' => [
  'name' => clienttranslate("Hades"),
  'expR' => 'E',
  'type' => 'planet ',
  'sp' => 3,
  't' => 'U',
  'w' => 6,
  'c' => 5,
  'slots' => 'n',
  'rslots' => 'F',
  'v' => 2,
  'tooltip' => clienttranslate("[Replenishing Fighter Slot]"),
],
        // --- gen php end escalation_planets ---
);



$this->materials = array(
        'planet_types' => [
                'E'=>clienttranslate('Fertile'),
                'M'=>clienttranslate('Metallic'),
                'A'=>clienttranslate('Advanced'),
                'D'=>clienttranslate('Diverse'),
                'P'=>clienttranslate('Prestige'),
                'U'=>clienttranslate('Utopian'),
        ],
        'planet_cost' => [
                'E'=>clienttranslate('Fertile Planet'),
                'EE'=>clienttranslate('Fertile Planet x 2'),
                'EEE'=>clienttranslate('Fertile Planet x 3'),
                'M'=>clienttranslate('Metallic Planet'),
                'MM'=>clienttranslate('Metallic Planet x 2'),
                'MMM'=>clienttranslate('Metallic Planet x 3'),
                'A'=>clienttranslate('Advanced Planet'),
                'AA'=>clienttranslate('Advanced Planet x 2'),
                'AAA'=>clienttranslate('Advanced Planet x 3'),
                'AEM'=>clienttranslate('1 Advanced, 1 Fertile, and 1 Metallic Planet'),
                'EN'=>clienttranslate('1 Fertile Planet and 1 any other type'),
                'MN'=>clienttranslate('1 Metallic Planet and 1 any other type'),
                'AN'=>clienttranslate('1 Advanced Planet and 1 any other type'),
        ],
        'icons' => [ 
                '' => clienttranslate('None'),
                'W' => clienttranslate('Warfare'),
                'S' => clienttranslate('Survey'),
                'R' => clienttranslate('Research'),
                'C' => clienttranslate('Colonize'),
                'P' => clienttranslate('Produce'),
                'T' => clienttranslate('Trade'),
                'h' => clienttranslate('+1 Hand Size'),
                'w' => clienttranslate('Water'),
                'f' => clienttranslate('Food'),
                's' => clienttranslate('Silicon'),
                'i' => clienttranslate('Iron'),
                'n' => clienttranslate('Any Resource'),
                'F' => clienttranslate('Fighter'),
                'D' => clienttranslate('Destroyer'),
                'B' => clienttranslate('Battlecruiser'),
        ],
        'role_icons' => ['W','S','R','C','P','T'],
        'fighter_icons' => ['F','D','B'], 
        'resources' => [
                '' => clienttranslate('None'),
                'w' => clienttranslate('Water'),
                'f' => clienttranslate('Food'),
                's' => clienttranslate('Silicon'),
                'i' => clienttranslate('Iron'),
                'n' => clienttranslate('Any Resource'),
                'a' => clienttranslate('Fighter Replenish'),
        ],
        /*-
        
        Automatic actions abbreviations

        */
        'actions' => [
                'd' => clienttranslate('Draw 1 card'),
                'e' => clienttranslate('Remove up to 1 card in hand from the game'),
                'i' => clienttranslate('Collect 1 Influence from the supply'),
                'L' => clienttranslate('RECON the Planet Deck for 1 card'),
                'K' => clienttranslate('RECON your Deck for any 1 card'),
                'F' => ('Collect 1 [Fighter] from the supply'),
                'D' => ('Collect 1 [Destroyer] from the supply'),
                'B' => ('Collect 1 [Battlecruiser] from the supply'),
                'S' => clienttranslate('Settle 1 Planet'),
                's'=>  clienttranslate('Settle 1 Planet OR +1 Colony'),
                'c'=>  clienttranslate('Add 1 Colony'),
                'a'=> clienttranslate('Attack 1 Planet'),
                'y'=> clienttranslate('Choose a resource type'),
                'R'=> clienttranslate('Research'),
                'T'=> clienttranslate('Gain Technology'),
                'o'=> ('Play extra action'),
                'O'=> ('Play extra role'),
                'u'=> ('Draw 1 planet'),
                'q'=> ('Keep 1 planet'),
                'Q'=> ('Discard rest of the planets from hand'),
                'l' =>('Select a role card to gain'), // politics
                't'=> ('Trade 1 resource'),
                'p'=> ('Produce 1 resource'),
                'g'=> clienttranslate('Select Permanent Technology to remove'),
        ],
);

/*- 
 
 Conventions for action and ability descriptions
 Field that may have them:
 'a' - card with action
 'r' - card with role
 'e' - card with permanent activatable ability
 'trig' - card with triggered abilities, array 
 
 xxx/yyy - OR action, player must chooise
 xxx>yyy - Pay>Get, player must pay to get something or to do something
 xxx. - ending dot means card triggert turn based effect (should probably remove now with setaside zonning)
 xxx.yyy - dot in the middle action is split in two part, first part must be sent to server to resolve first (i.e. draw card)
 xxx!    - confirmation required before submitting (i.e. when card removed permanently)
 xxx+    - action can be repeated any amount of times 
 event:yyy - triggered ability
 
 Trigger event format
 
 l-X leading role X
 d-X dissenting role X
 f-X following role X
 *-X playing role X
 'enter' - card enters play
 'settle' - settle a planet
 'attack' - attack a planet
 'peace' - peace treaty, shortcut for d-W:i
 
 */



foreach ($this->token_types as $id => &$info){
    $rowtype = $info ['type'];
    if (isset($info ['trig'])) {
        $trig = $info ['trig'];
        if ($info && !is_array($trig)) {
            if ($trig == 'peace') {
                $trig = "d-W:i";
            }
            $info ['trig'] = [ $trig ]; // re-wire
        }
    }
    if (isset($info ['rslots'])) {
        $info ['type'] .= " has_rslots rslots_".strlen($info ['rslots']);
    }
    if (isset($info ['v'])) {
        $info ['type'] .= " vp_".$info ['v'];
    }
    if (startsWith($rowtype,'planet')) { // NOI18N
        $info ['c'] = $info ['c'] ?? -1;
        $type = $info ['t'];
        $resources = $info ['slots'] ?? '';
        $info ['type'] .= " card_planet";
        if ($resources) {
            $info ['type'] .= " has_slots slots_$resources";
        }
        $info ['type'] .= " planet_${type}";
        if (array_key_exists('a', $info)) {
            //actionable
            $info ['type'] .= " actionable";
        }
        $icons = $info ['i'] ?? ''; // icons
        if ($icons) {
            for ($j = 0; $j < strlen($icons); $j++) {
                $c = $icons [$j];
                $info ['type'] .= " has_icon_$c";
            }
        }
    } else if (startsWith($rowtype, 'tech')) {
        // add translated planet type
        $req = $info['p'];
        $ptype = $req [0];
        if (isset($info['t'])) {
            $ptype=$info['t'];
        } else {
            $info['t']=$ptype;
        }
        $pcost = strlen($info ['p']);
     
        if (isset($info ['side'])) {
            $side = $info ['side'];
            if ($side != 0) {
                $info ['type'] .= " permanent";
                if ( !isset($info ['flip'])) {       // add flip
                    $x = strrpos($id, "_");
                    $num = substr($id, $x + 1) + 0;
                    if ($side == 1)
                        $num++;
                    else
                        $num--;
                    //card_tech_E_23
                    $flip_id = getPartsPrefix($id, -1) . "_" . $num;
                    $info ['flip'] = $flip_id;
                }
            }
        }
     
        // add icons for html
        $cost = $info ['b']; // research cost

        $icons = $info ['i'] ?? ''; // icons
 
        $info ['a'] = $info ['a'] ?? ''; // action text
        if ($icons) {
            for ($j = 0; $j < strlen($icons); $j++) {
                $c = $icons [$j];
                $info ['type'] .= " has_icon_$c";
                if ($c == 'w' || $c == 'f' || $c == 's' || $c == 'i'  || $c == 'n') {
                    $info ['type'] .= " as_resource as_resource_$c";
                    $info ['asr'] = $c;
                } else if ($c == 'F' || $c == 'D' || $c == 'B') {
                    $info ['type'] .= " as_fighter as_fighter_$c";
                    $info ['asf'] = $c;
                }
            }
        }
        $resources = $info ['slots'] ?? '';
        if ($resources) {
            $info ['type'] .= " has_slots slots_$resources";
        }
        if (isset($info ['bm'])) {
            $mcost = $info ['bm'] [0];
        }
        $mcost = $info ['bm'] ?? '';
        $info ['type'] .= " ptype_${ptype} pcost_${pcost} cost_${cost} req_${req}";
        if ($mcost)
            $info ['type'] .= " mcost_${mcost}";
        if (array_key_exists('e', $info)) {
            $info ['type'] .= " activatable";
        }
        if ($info ['a']) {
            //actionable
            $info ['type'] .= " actionable";
        }
    }
}

